# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zwElt6DUj1GGv8yF1AwVfP6AeQ-ycf2
"""

import pandas as pd
import scipy.stats as stats

cell_counts = pd.read_csv("/content/cell-count.csv")
cell_counts.head(10)

cell_counts = cell_counts.dropna(subset=['response'])
cell_counts['response'] = cell_counts['response'].map({'y': 1, 'n': 0})

cell_types = ['b_cell', 'cd8_t_cell', 'cd4_t_cell', 'nk_cell', 'monocyte']

results = []
for cell in cell_types:
    responders = cell_counts[cell_counts['response'] == 1][cell]
    non_responders = cell_counts[cell_counts['response'] == 0][cell]

    stat, p_value = stats.mannwhitneyu(responders, non_responders, alternative='two-sided')

    results.append({'Cell Type': cell, 'Mann-Whitney U': stat, 'p-value': p_value})

results_df = pd.DataFrame(results)

print(results_df)

significant_cells = results_df[results_df['p-value'] < 0.05]
print("\nSignificantly Different Cell Populations:")
print(significant_cells)

